config/routes.rb
Rails.application.routes.draw do
  #get 'cities/show'
  #get 'users/show'
  root 'gossips#index'
  get 'team', to: 'static_pages#home'
  get 'contact', to: 'static_pages#contact'
  get 'welcome/:first_name', to: 'static_pages#welcome'
  #get 'gossips/:id', to: 'static_pages#gossip', as: 'gossip'
  #get 'users/:id', to: 'static_pages#user', as: 'user'
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :gossip_tag_links
	has_many :tags, through: :gossip_tag_links
	validates :title, presence: true, length: { minimum: 3, maximum: 14, message: "title need 3 car. or less than 14 car"} 
  validates :content,presence: true
end

app/models/gossip_tag_link.rb
class GossipTagLink < ApplicationRecord
	belongs_to :gossip 
	belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	has_many :private_message_recipients
	has_many :recipients, class_name: "User", through: :private_message_recipients
end

app/models/private_message_recipient.rb
class PrivateMessageRecipient < ApplicationRecord
	belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip_tag_links
	has_many :gossips, through: :gossip_tag_links
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :private_message_recipients, foreign_key: 'recipient_id'
	has_many :received_messages, through: :private_message_recipients, source: :private_message
	validates :email, presence: true
	validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    
  end

  def show
  	puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60
    @city = City.find(params[:id])
  end

  def new
    
  end

  def create
    
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :show]
  
  def index
   @gossip = Gossip.all
  end

  def show
    if logged_in?
      @gossip = Gossip.find(params[:id])
    else
      flash[:notice] = "Connect to your account before !"
      redirect_to new_session_path
    end
  end

  def new
    if logged_in?
      @gossip = Gossip.new
    else
      flash[:notice] = "Connect to your account before !"
      redirect_to new_session_path
    end
  end

  def create
  	@gossip = Gossip.new('title' => params[:title], 'content' => params[:content], 'user_id' => current_user.id) 
    if @gossip.save 
      redirect_to '/'
    else
      render '/gossips/new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update('title' => params[:title], 'content' => params[:content], 'user_id' => @gossip.user_id)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Vous devez être connecté"
      redirect_to new_session_path
    end
  end

end

app/controllers/sessions_controller.rb
require 'bcrypt'
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user 
    	#&& @user.authenticate(params[:password_digest])
      session[:user_id] = @user.id
      log_in(@user)
      puts "Login is OK!"
      flash[:success] = "Utilisateur connecté !"
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(current_user.id)
    session[:user_id] = nil
    puts "Vous êtes déconnecté"
    flash[:notice] = "Utilisateur déconnecté !"
    redirect_to '/' 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

  def contact

  end

  def welcome
    @first_name = params['first_name']
  end

  def index
    @all_gossips = Gossip.all
  end

  def gossip
    @gossip = Gossip.find(params['id'])
  end

  def user
    @user = User.find(params['id'])
  end

end

app/controllers/users_controller.rb
require 'bcrypt'
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def index
  end

  def new
  end

  def create
    if params[:password_digest] == '' || params[:email] == ''
      flash[:Notice] = "Utilisateur non créé"
      render '/users/new'
     else
      @user = User.new
      @user = User.create('last_name': params[:last_name], 'first_name': params[:first_name], 'email': params[:email], 'age': params[:age], 'description': params[:description], 'city_id': params[:city].to_i, 'password': params[:password_digest])
      flash[:Notice] = "Utilisateur créé !"
      log_in(@user)
      redirect_to '/'
     end
  end

  def edit   
  end

  def update  
  end

  def destroy 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  # retourne true si l'user est loggé
  def logged_in?
    session[:user_id] != nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">The gossips from <%= @city.name %> !</h1>
    <p class="lead">Check what's going on there..</p>
  </div>
</div>

<% @city.users.each do |user| %>
  <div class="card mt-3">
		<div class="card-header">
			<h4 class="card-title"> <%= user.first_name %>  <%= user.last_name %> </h4>
		</div>
		<% user.gossips.each do |gossip| %>
			<div class="card-body">
				<p class="card-text"><%= gossip.title %></p>
				<p class="card-text"><%= gossip.content %></p>
			</div>
		<% end %>
		<div class="card-footer">
			<a class="card-link" href=#> Email : <%= user.email %> </a>
		</div>
	</div>
<% end %>

app/views/gossips/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Update a gossip</h1>
    <p class="lead">Please fill the form below</p>
  </div>
</div>

<div class="form-group">

    <%= form_tag url_for(action: 'update'), method: "put" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title , class: "form-control" %>
      <br /> <br />

      <%= label_tag 'Body' %>
      <%= text_area_tag 'content', @gossip.content , class: "form-control" %>
      <br /> <br />

      <%= submit_tag "Go", class: "btn btn-secondary bg-info'" %>

    <% end %>
 </div>

app/views/gossips/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">The last gossips !</h1>
    <p class="lead">Check what's going on..</p>
  </div>
</div>

<%= link_to "Want to add a gossip ?", new_gossip_path, class: "btn btn-outline-secondary btn-block" %>
<br/>
<div class="d-flex justify-content-around align-items-center flex-wrap">
	<% @gossip.each_with_index do |g,id| %>
	<div class="card mt-3 mb-3" style="width: 18rem;">
		<div class="card-header">
			<h5 class="card-title"><%=g.title%></h5>
			<h6 class="card-subtitle mb-2 text-muted"><%=g.user.first_name %></h6>
			<p class="card-text text-muted"><%=g.created_at %></p>
		</div>
		<div class="card-body">
			<p class="card-text"><%=g.content[0..100] %>...</p>
		</div>
		<div class="card-footer">
			<%= link_to 'Read more..', gossip_path(:id => g.id), { :class=>"card-link" } %>
		</div>
	</div>
	<% end %>
</div>

app/views/gossips/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Write a gossip</h1>
    <p class="lead">Fill the form</p>
  </div>
</div>

 <% if @gossip.errors.any? %>
  <div style="padding: 5px;">
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Ouups !!</h4>
      <p>Your gossip was not created:</p>
      <hr>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><p class="mb-0"><%= message %></p></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="form-group">

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', @gossip.title , class: "form-control" %>
      <br /> <br />

      <%= label_tag 'Body' %>
      <%= text_area_tag 'content', @gossip.content , class: "form-control" %>
      <br /> <br />

      <%= submit_tag "Go", class: "btn btn-secondary bg-info'" %>

    <% end %>
 </div>

app/views/gossips/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Here is a new gossip !</h1>
    <p class="lead">What's going on ?</p>
  </div>
</div>

<div class="card mt-3">
  <div class="card-header">
    <h3 class="card-title"><%= @gossip.title %> </h3>
    <h5 class="card-subtitle mb-2 text-muted"> <%= @gossip.user.first_name %><%= ", " %><%= link_to @gossip.user.city.name, city_path(@gossip.user.city_id), {:class=>"card-link"} %> </h5>
    <p class="card-text text-muted"><%= @gossip.created_at %></p>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @gossip.content %></p>
  </div>
  <div class="card-footer">
    <%= link_to "Author", user_path(@gossip.user_id), {:class=>"card-link"} %>
    <% if current_user.id == @gossip.user_id %>
    <%= link_to "Edit  -  ", edit_gossip_path(@gossip.id), {:class=>"card-link"} %>
    <%= link_to 'Delete', gossip_path(@gossip.id), method: 'delete' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

<body>
  <!-- NavBar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%= gossips_path%>">The Gossip Project</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">           
            <li class="nav-item">
            <%= link_to "Team", team_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% if logged_in?  %>
                <%= link_to "Sign-out", session_path(session[:user_id]), method: :delete, class: "nav-link" %>
              <% else %>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Connexion
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to "Register", new_user_path, class: "nav-link" %>
                    <%= link_to "Sign-in", new_session_path, class: "nav-link" %>
                  </div>
                </div>
              <% end %>
            </li>
          </ul>
        </div>
    </nav>
  <div class="container mt-3">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/contact.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Contact..</h1>
    <p class="lead"></p>
  </div>
</div>

app/views/static_pages/gossip.html.erb
<div class="card mt-3">
  <div class="card-header">
  	<h3 class="card-title"><%= @gossip.title %> </h3>
  	<h5 class="card-subtitle mb-2 text-muted"><%= @gossip.user.first_name %></h5>
  	<p class="card-text text-muted"><%= @gossip.created_at %></p>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @gossip.content %></p>
    <%= link_to "Profil de l'auteur", user_path(@gossip.user_id), {:class=>"card-link"} %>
  </div>
  <div class="card-footer">
  	<% @gossip.tags.each do |tag| %>
    <a class="card-link" href=#> <%= tag.title %> </a>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Gwada team..</h1>
    <p class="lead"></p>
  </div>
</div>

app/views/static_pages/welcome.html.erb
<h1>welcome <%= @first_name %></h1>

app/views/users/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Register</h1>
    <p class="lead">Please register with an e-mail & password</p>
  </div>
</div>

<div class="form-group">
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag '* e-mail ' %>
  <%= text_field_tag 'email', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag ' * Password ' %>
  <%= text_field_tag 'password_digest', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag 'First name ' %>
  <%= text_field_tag 'first_name', nil, class: "form-control" %>
  <br /> <br />

  <%= label_tag 'Last name ' %>
  <%= text_field_tag 'last_name', nil, class: "form-control" %>
  <br /> <br />
  
  <%= label_tag 'Description ' %>
  <%= text_area_tag 'description', nil, class: "form-control" %>
  <br /> <br />
  
  <%= label_tag 'Age ' %>
  <%= text_field_tag 'age', nil, class: "form-control" %>
  <br /> <br />

  <select class="field-tag form-item select-tag" name="city">
  <% City.all.each do |city| %>
  <option value="<%= city.id %>"><%= city.name %></option>
  <% end %>
  </select>

  <%= submit_tag "Go", class: "btn btn-secondary " %>

<% end %>

</div>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Author details ! </h1>
    <p class="lead">Know more about this author..</p>
  </div>
</div>

<div class="card mt-3">
	<div class="card-header">
		<h4 class="card-title"> <%= @user.first_name %>  <%= @user.last_name %> </h4>
		<h6 class="card-subtitle mb-2 text-muted"> <%= link_to @user.city.name, city_path(@user.city_id), {:class=>"card-link"} %> </h6>
		<h6 class="card-subtitle mb-2 text-muted"> <%= @user.age %> ans </h6>
	</div>
	<div class="card-body">
		<p class="card-text"><%= @user.description %></p>
	</div>
	<div class="card-footer">
		<a class="card-link" href=#> Email : <%= @user.email %> </a>
	</div>
</div>